import { Department, Position, Employee } from "@/types";

export interface DepartmentWithData extends Department {
  positions: (Position & { employees?: Employee[] })[];
}

export const HAZINIY_MAIN_MISSION =
  "HAR BIR SHAXS GO'ZAL XULQLI VA O'Z SOHASIGA MUNOSIB ILM-SALOHIYATLI BO'LISHI YO'LIDA QILINADIGAN ISHLARNI SAMIMIY BAJARISH\nJAMIYATNING HAR BIR QATLAMI VA UNDAGI HAR BIR SOHANI ISLOH QILISH YO'LIDA QILINADIGAN ISHLARNI SAMIMIY AMALGA OSHIRISH.";

export const DEFAULT_TEST_EMPLOYEES: (Employee & {
  position?: (Position & { department?: Department }) | null;
})[] = [
  {
    id: "asoschi-test-emp",
    position_id: "pos-bosh-1",
    full_name: "Vaqtinchalik ma'lumot — admin panel orqali to'ldiriladi",
    phone: null,
    photo_url: null,
    hired_at: null,
    personal_yqm: "KORXONA STRATEGIYASI, MISSIYASI VA YUKSALISHI",
    resume: "Ushbu profil Asoschi lavozimi uchun vaqtinchalik yaratilgan. Haqiqiy ma'lumotlar Admin panel orqali to'ldiriladi.",
    portfolio_links: [],
    created_at: new Date().toISOString(),
    position: {
      id: "pos-bosh-1",
      department_id: "dept-boshqaruv",
      title: "ASOSCHI",
      yqm_text: "KORXONA STRATEGIYASI, MISSIYASI VA YUKSALISHI YO'LIDA SAMIMIY XIZMAT QILISH.",
      status: "mavjud",
      sort_order: 1,
      created_at: new Date().toISOString(),
      department: {
        id: "dept-boshqaruv",
        name: "Boshqaruv",
        color_hex: "#0F172A",
        sort_order: 0,
        yqm_text: "MARKAZ STRATEGIYASI, MISSIYASI VA BARCHA BO'LIMLAR INTEGRATSIYASI",
        created_at: new Date().toISOString(),
      },
    },
  },
  {
    id: "menejer-test-emp",
    position_id: "pos-bosh-2",
    full_name: "Vaqtinchalik ma'lumot — admin panel orqali to'ldiriladi",
    phone: null,
    photo_url: null,
    hired_at: null,
    personal_yqm: "OPERATSION BOSHQARUV VA BARCHA BO'LIMLAR INTEGRATSIYASI",
    resume: "Ushbu profil Menejer lavozimi uchun vaqtinchalik yaratilgan. Haqiqiy ma'lumotlar Admin panel orqali to'ldiriladi.",
    portfolio_links: [],
    created_at: new Date().toISOString(),
    position: {
      id: "pos-bosh-2",
      department_id: "dept-boshqaruv",
      title: "MENEJER",
      yqm_text: "OPERATSION BOSHQARUV VA BARCHA BO'LIMLAR INTEGRATSIYASI",
      status: "mavjud",
      sort_order: 2,
      created_at: new Date().toISOString(),
      department: {
        id: "dept-boshqaruv",
        name: "Boshqaruv",
        color_hex: "#0F172A",
        sort_order: 0,
        yqm_text: "MARKAZ STRATEGIYASI, MISSIYASI VA BARCHA BO'LIMLAR INTEGRATSIYASI",
        created_at: new Date().toISOString(),
      },
    },
  },
];

export const DEFAULT_SHEETS_DEPARTMENTS: DepartmentWithData[] = [
  {
    id: "dept-boshqaruv",
    name: "Boshqaruv",
    color_hex: "#0F172A",
    sort_order: 0,
    yqm_text: "Markaz strategiyasi, missiyasi va barcha bo'limlar integratsiyasi",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-bosh-1",
        department_id: "dept-boshqaruv",
        title: "ASOSCHI",
        yqm_text: "KORXONA STRATEGIYASI, MISSIYASI VA YUKSALISHI",
        status: "mavjud",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [DEFAULT_TEST_EMPLOYEES[0]],
      },
      {
        id: "pos-bosh-2",
        department_id: "dept-boshqaruv",
        title: "MENEJER",
        yqm_text: "OPERATSION BOSHQARUV VA BARCHA BO'LIMLAR INTEGRATSIYASI",
        status: "mavjud",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [DEFAULT_TEST_EMPLOYEES[1]],
      },
    ],
  },
  {
    id: "dept-moliya",
    name: "Moliya",
    color_hex: "#B45309",
    sort_order: 1,
    yqm_text: "KORXONA MOLIYAVIY HOLATINING ADOLATLI TASHKIL ETILISHI",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-mol-1",
        department_id: "dept-moliya",
        title: "Bo'lim boshlig'i",
        yqm_text: "MOLIYA BO'LIMIGA YUKLATILGAN VAZIFALARNI HAR QANDAY HOLATDA HAM ADOLATLI BAJARILISHI YO'LIDA XIZMAT QILISH",
        status: "rejalashtirilgan",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mol-2",
        department_id: "dept-moliya",
        title: "Moliyachi",
        yqm_text: "KORXONADA PUL OQIMINI TO'G'RI BO'LISHI VA ENG KERAKLI BO'LGAN SOHAGA PUL SARFLANISHI YO'LIDA QILINADIGAN ISHLARNI SAMIMIY BAJARISH",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mol-3",
        department_id: "dept-moliya",
        title: "Buxgalter",
        yqm_text: "KOROXONADAGI BARCHA PULGA DOIR ISHLAR HISOBOTINI JAMLAB BORISH.",
        status: "rejalashtirilgan",
        sort_order: 3,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-marketing",
    name: "Marketing",
    color_hex: "#1D4ED8",
    sort_order: 2,
    yqm_text: "KORXONANING ASOSIY FAOLIYATI VA IMKONIYATLARINI MIJOZLARGA TO‘G‘RI YETKAZISH VA SIFATLI LIDLAR SONINI OSHIRISH YO'LIDA QILINADIGAN ISHLARNI SAMIMIY BAJARISH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-mkt-1",
        department_id: "dept-marketing",
        title: "Bo'lim boshlig'i",
        yqm_text: "MARKETING BO'LIMIGA YUKLATILGAN VAZIFALARNI HAR QANDAY HOLATDA HAM BAJARILISHI YO'LIDA SAMIMIY XIZMAT QILISH.",
        status: "rejalashtirilgan",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mkt-2",
        department_id: "dept-marketing",
        title: "Marketolog",
        yqm_text: "KORXONANI O'Z VAQTIDA REJALI RAVISHDA LIDLAR BILAN TO'LDIRISH UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mkt-3",
        department_id: "dept-marketing",
        title: "SMM menejer",
        yqm_text: "IJTIMOIY TARMOQLARNI YURGAZISH ORQALI MUROJAATLAR SONINI OSHIRISH YO'LIDA SAMIMIY XIZMAT QILISH.",
        status: "rejalashtirilgan",
        sort_order: 3,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mkt-4",
        department_id: "dept-marketing",
        title: "Dizayner",
        yqm_text: "MARKETING UCHUN KERAK BO'LADIGAN GRAFIK DIZAYNLARNI TAYYORLASH.",
        status: "rejalashtirilgan",
        sort_order: 4,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mkt-5",
        department_id: "dept-marketing",
        title: "Video montajor",
        yqm_text: "MARKETING UCHUN KERAK BO'LADIGAN VIDEOLARNI SYOMKA VA MONTAJ BO'LISHI UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 5,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-sotuv",
    name: "Sotuv",
    color_hex: "#C2410C",
    sort_order: 3,
    yqm_text: "MIJOZLAR MUAMMOLARINI ANIQLAB, ULARGA SAMIMIY YECHIM TAKLIF QILISH VA SOTUV UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-sotuv-1",
        department_id: "dept-sotuv",
        title: "Administrator",
        yqm_text: "MIJOZLAR MUAMMOLARINI ANIQLAB, ULARGA SAMIMIY YECHIM TAKLIF QILISH VA SOTUV UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH",
        status: "mavjud",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-sotuv-2",
        department_id: "dept-sotuv",
        title: "Sotuv bo'lim boshlig'i",
        yqm_text: "SOTUVLAR O'Z VAQTIDA REJA ASOSIDA BO'LISHI UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-sotuv-3",
        department_id: "dept-sotuv",
        title: "Sotuv menejeri",
        yqm_text: "QAYTA SOTUVLAR AMALGA OSHISHI UCHUN QILINADIGAN ISHLARNI SIDQIDILDAN BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 3,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-sotuv-4",
        department_id: "dept-sotuv",
        title: "Kiruvchi admin",
        yqm_text: "MUROJAAT QILGAN MIJOZLARNI KORXONAGA SINOV DARSIGA KELISHI UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 4,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-sotuv-5",
        department_id: "dept-sotuv",
        title: "Chiquvchi admin",
        yqm_text: "SINOV DARSIGA KELGAN MIJOZLARNI TO'LOV QILISHLARI UCHUN TAQDIMOT QILIB SOTUVNI AMALGA OSHIRISH UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 5,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-oquv",
    name: "O'quv",
    color_hex: "#047857",
    sort_order: 4,
    yqm_text: "O'QUVCHILARGA ILMNING MOHIYATI VA QIYMATINI TUSHUNTIRISH, SIFATLI TA'LIM BERISH VA ULARDA GO'ZAL AXLOQNI SHAKLLANTIRISH YO'LIDA QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-oquv-1",
        department_id: "dept-oquv",
        title: "Ustoz",
        yqm_text: "KORXONADA BELGILANGAN ME'ZONLAR ASOSIDA MIJOZLAR TA'LIM-TARBIYA OLISHI YO'LIDA SIDQIDILDAN XIZMAT QILISH.",
        status: "mavjud",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-oquv-2",
        department_id: "dept-oquv",
        title: "Support",
        yqm_text: "USTOZGA YORDAM BERISH UCHUN MIJOZLARNI BILIM OLISHIGA KO'MAKLASHISH",
        status: "mavjud",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-oquv-3",
        department_id: "dept-oquv",
        title: "Bo'lim boshlig'i",
        yqm_text: "O'QUV BO'LIMIGA YUKLATILGAN VAZIFALARNI HAR QANDAY HOLATDA HAM BAJARILISHI YO'LIDA SAMIMIY XIZMAT QILISH.",
        status: "rejalashtirilgan",
        sort_order: 3,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-oquv-4",
        department_id: "dept-oquv",
        title: "Metodist",
        yqm_text: "DARSLIKLARDA FOYDALANISH UCHUN YANGI METODLAR TUZIB CHIQISH VA ULARNI AMALDA QO'LLANISHI UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 4,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-oquv-5",
        department_id: "dept-oquv",
        title: "Katta ustoz",
        yqm_text: "METODIST TOMONIDAN BERILGAN METODLARNI KORXONADA JORIY QILISH VA USTOZLARNI MALAKASINI OSHIRISHGA KO'MAKLASHISH UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 5,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-oquv-6",
        department_id: "dept-oquv",
        title: "Assistent",
        yqm_text: "O'QUV BO'LIMI UCHUN KERAKLI MATERIALLARNI TAYYORLASH UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 6,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-hr",
    name: "HR",
    color_hex: "#6D28D9",
    sort_order: 5,
    yqm_text: "KORXONADA QADRIYATLARIMIZGA MOS KADRLAR BILAN TO'LDIRISH VA KADRLAR BILAN MUAMMO BO'LMASLIGI UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-hr-1",
        department_id: "dept-hr",
        title: "Bo'lim boshlig'i",
        yqm_text: "HR BO'LIMIGA YUKLATILGAN VAZIFALARNI HAR QANDAY HOLATDA HAM BAJARILISHI YO'LIDA SAMIMIY XIZMAT QILISH.",
        status: "rejalashtirilgan",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-hr-2",
        department_id: "dept-hr",
        title: "HR menejer",
        yqm_text: "KORXONA UCHUN KERAKLI BO'LGAN KADRLARNI TOPISH, TARBIYALASH VA XODIMLARNI OLIB QOLISH UCHUN SAMIMIY XIZMAT QILISH.",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-texnik",
    name: "Texnik",
    color_hex: "#475569",
    sort_order: 6,
    yqm_text: "KORXONADA XODIMLAR VA MIJOZLAR UCHUN XAVFSIZ MUHIT BO'LISHI UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-tex-1",
        department_id: "dept-texnik",
        title: "Bo'lim boshlig'i",
        yqm_text: "TEXNIK BO'LIMIGA YUKLATILGAN VAZIFALARNI HAR QANDAY HOLATDA HAM BAJARILISHI YO'LIDA SAMIMIY XIZMAT QILISH.",
        status: "rejalashtirilgan",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-tex-2",
        department_id: "dept-texnik",
        title: "Qorovul",
        yqm_text: "KORXONA XAVFSIZLIGI YO'LIDA QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-tex-3",
        department_id: "dept-texnik",
        title: "Farrosh",
        yqm_text: "O'QUVCHILAR TOZA HUDUDDA TA'LIM OLISHI UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH.",
        status: "rejalashtirilgan",
        sort_order: 3,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-yuridik",
    name: "Yuridik",
    color_hex: "#881337",
    sort_order: 7,
    yqm_text: "KORXONA FAOLIYATI YURIDIK JIHATDAN HAVFSIZ BO'LISHI UCHUN QILINADIGAN ISHLARNI SAMIMIY BAJARISH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-yur-1",
        department_id: "dept-yuridik",
        title: "Bo'lim boshlig'i",
        yqm_text: "YURIDIK BO'LIMIGA YUKLATILGAN VAZIFALARNI HAR QANDAY HOLATDA HAM BAJARILISHI YO'LIDA QILINADIGAN ISHLARNI SAMIMIY BAJARISH",
        status: "rejalashtirilgan",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-yur-2",
        department_id: "dept-yuridik",
        title: "Yurist",
        yqm_text: "KORXONANI YURIDIK JIHATDAN TO'G'RI FAOLIYAT OLIB BORISHI UCHUN BARCHA ISHLARNI BAJARILISHI VA XAT-HUJJATLAR BILAN BOG'LIQ MASALALARNI SAMIMIY BAJARISH",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
];
