import { Department, Position, Employee } from "@/types";

export interface DepartmentWithData extends Department {
  positions: (Position & { employees?: Employee[] })[];
}

export const HAZINIY_MAIN_MISSION =
  "YUQORI DARAJALI XIZMAT KO'RSATISH ORQALI XALQIMIZ ORASIDA GO'ZAL XULQLI, AQLLI TALABALAR YETISHIB CHIQISHI VA ILM YUKSAK DARAJAGA KO'TARILISHIGA O'Z HISSAMIZNI QO'SHISH\nHAR BIR TALABAGA INDIVIDUAL YONDASHUV VA ZAMONAVIY TA'LIM METODLARI ASOSIDA KELAJAK KASBLARINI O'RGATISH\nMILLIY VA UMUMINSONIY QADRIYATLARGA TAYANGAN HOLDA TIZIMLI VA SIFATLI BILIM BERISH";

export const DEFAULT_TEST_EMPLOYEES: (Employee & {
  position?: (Position & { department?: Department }) | null;
})[] = [
  {
    id: "asoschi-test-emp",
    position_id: "pos-bosh-1",
    full_name: "Vaqtinchalik ma'lumot — admin panel orqali to'ldiriladi",
    phone: null,
    photo_url: null,
    hired_at: null,
    personal_yqm: "KORXONA STRATEGIYASI, MISSIYASI VA YUKSALISHI",
    resume: "Ushbu profil Asoschi lavozimi uchun vaqtinchalik yaratilgan. Haqiqiy ma'lumotlar Admin panel orqali to'ldiriladi.",
    portfolio_links: [],
    created_at: new Date().toISOString(),
    position: {
      id: "pos-bosh-1",
      department_id: "dept-boshqaruv",
      title: "ASOSCHI",
      yqm_text: "KORXONA STRATEGIYASI, MISSIYASI VA YUKSALISHI",
      status: "mavjud",
      sort_order: 1,
      created_at: new Date().toISOString(),
      department: {
        id: "dept-boshqaruv",
        name: "Boshqaruv",
        color_hex: "#0F172A",
        sort_order: 0,
        yqm_text: "MARKAZ STRATEGIYASI, MISSIYASI VA BARCHA BO'LIMLAR INTEGRATSIYASI",
        created_at: new Date().toISOString(),
      },
    },
  },
  {
    id: "menejer-test-emp",
    position_id: "pos-bosh-2",
    full_name: "Vaqtinchalik ma'lumot — admin panel orqali to'ldiriladi",
    phone: null,
    photo_url: null,
    hired_at: null,
    personal_yqm: "OPERATSION BOSHQARUV VA BARCHA BO'LIMLAR INTEGRATSIYASI",
    resume: "Ushbu profil Menejer lavozimi uchun vaqtinchalik yaratilgan. Haqiqiy ma'lumotlar Admin panel orqali to'ldiriladi.",
    portfolio_links: [],
    created_at: new Date().toISOString(),
    position: {
      id: "pos-bosh-2",
      department_id: "dept-boshqaruv",
      title: "MENEJER",
      yqm_text: "OPERATSION BOSHQARUV VA BARCHA BO'LIMLAR INTEGRATSIYASI",
      status: "mavjud",
      sort_order: 2,
      created_at: new Date().toISOString(),
      department: {
        id: "dept-boshqaruv",
        name: "Boshqaruv",
        color_hex: "#0F172A",
        sort_order: 0,
        yqm_text: "MARKAZ STRATEGIYASI, MISSIYASI VA BARCHA BO'LIMLAR INTEGRATSIYASI",
        created_at: new Date().toISOString(),
      },
    },
  },
];

export const DEFAULT_SHEETS_DEPARTMENTS: DepartmentWithData[] = [
  {
    id: "dept-boshqaruv",
    name: "Boshqaruv",
    color_hex: "#0F172A",
    sort_order: 0,
    yqm_text: "Markaz strategiyasi, missiyasi va barcha bo'limlar integratsiyasi",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-bosh-1",
        department_id: "dept-boshqaruv",
        title: "ASOSCHI",
        yqm_text: "KORXONA STRATEGIYASI, MISSIYASI VA YUKSALISHI",
        status: "mavjud",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [DEFAULT_TEST_EMPLOYEES[0]],
      },
      {
        id: "pos-bosh-2",
        department_id: "dept-boshqaruv",
        title: "MENEJER",
        yqm_text: "OPERATSION BOSHQARUV VA BARCHA BO'LIMLAR INTEGRATSIYASI",
        status: "mavjud",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [DEFAULT_TEST_EMPLOYEES[1]],
      },
    ],
  },
  {
    id: "dept-moliya",
    name: "Moliya",
    color_hex: "#B45309",
    sort_order: 1,
    yqm_text: "KORXONANI KERAKLI VAQTDA YETARLI PUL MIQDORI BILAN TAMINLASH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-mol-1",
        department_id: "dept-moliya",
        title: "Bo'lim boshlig'i",
        yqm_text: "Moliya bo'limiga yuklatilgan vazifalarni har qanday holatda ham bajarilishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mol-2",
        department_id: "dept-moliya",
        title: "Moliyachi",
        yqm_text: "Korxonada pul oqimini to'g'ri bo'lishini ta'minlash va eng kerakli bo'lgan sohaga pul sarflanishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mol-3",
        department_id: "dept-moliya",
        title: "Buxgalter",
        yqm_text: "Koroxonadagi barcha pulga doir ishlar xisobotini jamlab borish",
        status: "rejalashtirilgan",
        sort_order: 3,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-marketing",
    name: "Marketing",
    color_hex: "#1D4ED8",
    sort_order: 2,
    yqm_text: "KORXONANI SIFATLI LIDLAR BILAN TA'MINLASH VA BOZORDA O'RNINI SAQLAB QOLISH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-mkt-1",
        department_id: "dept-marketing",
        title: "Bo'lim boshlig'i",
        yqm_text: "Marketing bo'limiga yuklatilgan vazifalarni har qanday holatda ham bajarilishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mkt-2",
        department_id: "dept-marketing",
        title: "Marketolog",
        yqm_text: "Korxonani o'z vaqtida rejali ravishda lidlar bilan ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mkt-3",
        department_id: "dept-marketing",
        title: "SMM menejer",
        yqm_text: "Ijtimoiy tarmoqlarni yurgazish orqali murojaatlar sonini oshirish",
        status: "rejalashtirilgan",
        sort_order: 3,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mkt-4",
        department_id: "dept-marketing",
        title: "Dizayner",
        yqm_text: "Marketing uchun kerak bo'ladigan grafik dizaynlarni tayyorlash",
        status: "rejalashtirilgan",
        sort_order: 4,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-mkt-5",
        department_id: "dept-marketing",
        title: "Video montajor",
        yqm_text: "Marketing uchun kerak bo'ladigan videolarni syomka va montaj bo'lishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 5,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-sotuv",
    name: "Sotuv",
    color_hex: "#C2410C",
    sort_order: 3,
    yqm_text: "KORXONADA SOTUVLARNI AMALGA OSHIRISH ORQALI DAROMADNI KO'PAYTIRISH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-sotuv-1",
        department_id: "dept-sotuv",
        title: "Administrator",
        yqm_text: "1) Menyu olgan mijozlarni sinov darsga kelishini ta'minlash,\n2) Sinov darsiga kelgan mijozlarga sotuvni amalga oshirib to'lovni yig'ish,\n3) Tartib intizomni ta'minlash,\n4) Qaynoq lidlar o'z vaqtida javob berilishini ta'minlash,\n5) Qayta sotuvlar amalga oshirilishini ta'minlash",
        status: "mavjud",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-sotuv-2",
        department_id: "dept-sotuv",
        title: "Sotuv bo'lim boshlig'i",
        yqm_text: "Sotuvlar o'z vaqtida reja asosida bo'lishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-sotuv-3",
        department_id: "dept-sotuv",
        title: "Sotuv menejeri",
        yqm_text: "Qayta sotuvlar amalga oshishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 3,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-sotuv-4",
        department_id: "dept-sotuv",
        title: "Kiruvchi admin",
        yqm_text: "Murojaat qilgan mijozlarni korxonaga sinov darsiga kelishlarini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 4,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-sotuv-5",
        department_id: "dept-sotuv",
        title: "Chiquvchi admin",
        yqm_text: "Sinov darsiga kelgan mijozlarni to'lov qilishlari uchun taqdimot qilib sotuvni amalga oshirish",
        status: "rejalashtirilgan",
        sort_order: 5,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-oquv",
    name: "O'quv",
    color_hex: "#047857",
    sort_order: 4,
    yqm_text: "MIJOZLARGA XIZMAT KO'RSATISH VA SARAFAN ORQALI MIJOZLAR SONINI YANADA OSHIRISH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-oquv-1",
        department_id: "dept-oquv",
        title: "Ustoz",
        yqm_text: "Korxonada belgilangan metodlar asosida mijozlar bilim olishini ta'minlash",
        status: "mavjud",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-oquv-2",
        department_id: "dept-oquv",
        title: "Support",
        yqm_text: "Ustozga yordam berish uchun mijozlarni bilim olishiga ko'maklashish",
        status: "mavjud",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-oquv-3",
        department_id: "dept-oquv",
        title: "Bo'lim boshlig'i",
        yqm_text: "O'quv bo'limiga yuklatilgan vazifalarni har qanday holatda ham bajarilishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 3,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-oquv-4",
        department_id: "dept-oquv",
        title: "Metodist",
        yqm_text: "Darsliklarda foydalanish uchun yangi metodlar tuzib chiqish va ularni amalda qo'llanishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 4,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-oquv-5",
        department_id: "dept-oquv",
        title: "Katta ustoz",
        yqm_text: "Metodist tomonidan berilgan metodlarni korxonada joriy qilish va ustozlarni malakasini oshirishga ko'maklashish",
        status: "rejalashtirilgan",
        sort_order: 5,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-oquv-6",
        department_id: "dept-oquv",
        title: "Assistent",
        yqm_text: "O'quv bo'limi uchun kerakli materiallarni tayyorlash",
        status: "rejalashtirilgan",
        sort_order: 6,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-hr",
    name: "HR",
    color_hex: "#6D28D9",
    sort_order: 5,
    yqm_text: "KORXONADA KADRLAR BILAN MUAMMO BO'LMASLIGINI TAMINLASH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-hr-1",
        department_id: "dept-hr",
        title: "Bo'lim boshlig'i",
        yqm_text: "HR bo'limiga yuklatilgan vazifalarni har qanday holatda ham bajarilishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-hr-2",
        department_id: "dept-hr",
        title: "HR menejer",
        yqm_text: "Korxona uchun kerakli bo'lgan kadrlarni topish , tarbiyalash va xodimlarni olib qolish",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-texnik",
    name: "Texnik",
    color_hex: "#475569",
    sort_order: 6,
    yqm_text: "KORXONANI MIJOZ VA XODIMLAR UCHUN QULAY VA XAVFSIZ JOY BO'LISHINI TAMINLASH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-tex-1",
        department_id: "dept-texnik",
        title: "Bo'lim boshlig'i",
        yqm_text: "Texnik bo'limiga yuklatilgan vazifalarni har qanday holatda ham bajarilishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-tex-2",
        department_id: "dept-texnik",
        title: "Qorovul",
        yqm_text: "Korxona xavfsizligini taminlash",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-tex-3",
        department_id: "dept-texnik",
        title: "Farrosh",
        yqm_text: "Korxona tozaligini taminlash",
        status: "rejalashtirilgan",
        sort_order: 3,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
  {
    id: "dept-yuridik",
    name: "Yuridik",
    color_hex: "#881337",
    sort_order: 7,
    yqm_text: "KORXONANI FOALIYATI YURIDIK JIXATDAN XAVFSIZ BO'LISHINI TAMINLASH",
    created_at: new Date().toISOString(),
    positions: [
      {
        id: "pos-yur-1",
        department_id: "dept-yuridik",
        title: "Bo'lim boshlig'i",
        yqm_text: "Yuridik bo'limiga yuklatilgan vazifalarni har qanday holatda ham bajarilishini ta'minlash",
        status: "rejalashtirilgan",
        sort_order: 1,
        created_at: new Date().toISOString(),
        employees: [],
      },
      {
        id: "pos-yur-2",
        department_id: "dept-yuridik",
        title: "Yurist",
        yqm_text: "Korxonani yuridik jixatdan to'g'ri faoliyat olib borishi uchun barcha ishlarni bajarilishini taminlash va xat xujjatlar bilan bog'liq masalalarni bajarish",
        status: "rejalashtirilgan",
        sort_order: 2,
        created_at: new Date().toISOString(),
        employees: [],
      },
    ],
  },
];
